#guessing game using random package of python

import random

def guess(x):
    #generating random number using random module between 1, and x
    random_number= random.randint(1,x)
    guess=0

    #using while loop to guess whether user input matches the number generated by Computer or not
    while guess !=random_number:
        guess=int(input(f"Guess a number between 1 and {x}:"))
        if guess < random_number:
            print("Sorry, guess again. Too low.")
        elif guess > random_number:
            print("Sorry, guess again. Too high.")
    
    print(f"Jackpot!! You guessed it right!! The number was {random_number}")


guess(10)